admin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    # apps
    path("", include("apps.website.urls", namespace="website")),
    path("showcase/", include("apps.showcase.urls", namespace="showcase")),
    path("api/", include("apps.api.urls")),
    path("api/speech/", include("apps.speech.urls")),
    # Static pages
    path("info/", TemplateView.as_view(template_name="info.html"), name="info"),
    path(
        "privacy/", TemplateView.as_view(template_name="privacy.html"), name="privacy"
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    # Third party libraries
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/website/urls.py
from django.urls import path, register_converter
from django.utils import timezone

from . import views


class DateTimeConverter:
    regex = r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}"

    @staticmethod
    def to_python(value):
        time = timezone.datetime.strptime(value, "%Y-%m-%dT%H:%M:%S")
        return timezone.make_aware(time)

    @staticmethod
    def to_url(value):
        return value


register_converter(DateTimeConverter, "datetime")

app_name = "website"
urlpatterns = [
    path("", views.Map.as_view()),
    path("map/", views.Map.as_view(), name="map"),
    path("share/", views.Share.as_view(), name="share"),
    path("history/", views.HistoryMap.as_view(), name="history"),
    path("history/<datetime:timestamp>/", views.HistoryMap.as_view(), name="history"),
]

apps/website/models.py
import random
import textwrap

from django.contrib.gis.db import models
from django.contrib.gis.db.models.aggregates import Union
from django.contrib.gis.db.models.functions import Centroid, Distance
from django.contrib.gis.geos import Point
from django.db.models import F, Max, Q, Sum
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.utils.translation import gettext as _

from .fields import UniqueBooleanField
from .tools.geo import coordinates, mercator_coordinates


class LocationModel(models.Model):
    location = models.PointField()

    @property
    def latitude(self) -> float:
        return self.location.y

    @property
    def longitude(self) -> float:
        return self.location.x

    @property
    def coordinates(self) -> list[float, float]:
        return coordinates(self.location)

    @property
    def mercator_coordinates(self) -> tuple[float, float]:
        return mercator_coordinates(self.latitude, self.longitude)

    def __str__(self):
        return f"({self.latitude:.4f}, {self.longitude:.4f})"

    class Meta:
        abstract = True


class TitledModel(models.Model):
    slug = models.SlugField(unique=True)
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    class Meta:
        abstract = True


class LeafletProvider(TitledModel):
    name = models.CharField(
        max_length=100,
        null=True,
        blank=True,
        help_text=_("The short name to use with provider.js"),
    )
    url = models.URLField(
        max_length=150,
        null=True,
        blank=True,
        help_text=_("The url for a generic leaflet provider"),
    )

    def as_json(self) -> dict:
        return {"url": self.url, "name": self.name}

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=Q(name__isnull=False) | Q(url__isnull=False),
                name="either_name_or_url_not_null",
                violation_error_message=_(
                    _("Either name or url should be set to a valid value")
                ),
            )
        ]


class Place(LocationModel):
    slug = models.SlugField(unique=True, null=True, blank=True)
    title = models.CharField(max_length=100, blank=True)

    description = models.TextField(max_length=500, blank=True)

    @classmethod
    def get_nearest(cls, location: Point) -> "Place":
        return (
            cls.objects.annotate(distance=Distance("location", location))
            .order_by("distance")
            .first()
        )

    def get_frequencies(self, min_frequency: int = 2) -> list[list[str, float]]:
        """Return a list of [word, frequency] with the latest normalized"""
        frequencies = self.word_frequencies.filter(
            frequency__gte=min_frequency, word__visible=True
        ).order_by("-frequency")[:50]
        max_ = frequencies.aggregate(Max("frequency"))["frequency__max"]
        return [[wf.word.text, wf.frequency / max_] for wf in frequencies]

    def as_json(self):
        return {"coordinates": self.coordinates, "frequencies": self.get_frequencies()}

    def __str__(self):
        if self.title:
            return self.title
        if self.slug:
            return self.slug
        return LocationModel.__str__(self)


class Word(models.Model):
    text = models.CharField(max_length=100, unique=True)
    visible = models.BooleanField(
        default=True,
        help_text="Set to False to hide this word in maps",
    )

    def __str__(self):
        return ("🚩 " if not self.visible else "") + self.text


class Share(LocationModel):
    timestamp = models.DateTimeField(default=timezone.now)
    message = models.TextField(max_length=500)
    landscape = models.ForeignKey("Landscape", on_delete=models.CASCADE)

    place = models.ForeignKey(
        Place,
        related_name="shares",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    words = models.ManyToManyField(Word, related_name="shares", blank=True)

    def __str__(self):
        message = textwrap.shorten(self.message, width=20, placeholder="...")
        return f"{super().__str__()} [{message}]"


class WordFrequency(models.Model):
    word = models.ForeignKey(
        Word,
        on_delete=models.CASCADE,
        related_name="place_frequencies",
    )
    place = models.ForeignKey(
        Place,
        on_delete=models.CASCADE,
        related_name="word_frequencies",
    )
    frequency = models.PositiveIntegerField(default=0)

    class Meta:
        verbose_name_plural = "Word Frequencies"
        ordering = ("-frequency",)
        constraints = [
            models.UniqueConstraint(
                fields=("word", "place"), name="WordFrequency uniqueness"
            )
        ]

    @classmethod
    def top_words(cls) -> list[tuple[str, int]]:
        query = cls.objects.values("word").annotate(total=Sum("frequency"))
        query = query.order_by("-total")[:10]
        return [(obj["word"], obj["total"]) for obj in query]

    @classmethod
    def create_random(cls, place: Place = None):
        if place is None:
            place = random.choice(Place.objects.all())
        sample, created = cls.objects.get_or_create(
            word=f"WORD{random.randint(0, 20):02d}", place=place
        )
        sample.frequency = F("frequency") + random.randint(1, 10)
        sample.save()

    def __str__(self):
        return f"({self.word} | {self.place})"


class Logo(models.Model):
    name = models.CharField(max_length=150, blank=True)
    image = models.ImageField(
        upload_to="logos/", height_field="height", width_field="width"
    )
    width = models.PositiveSmallIntegerField(null=True, blank=True, editable=False)
    height = models.PositiveSmallIntegerField(null=True, blank=True, editable=False)

    @property
    def url(self):
        return self.image.url

    def __str__(self):
        return self.name if self.name else super().__str__()


class Landscape(TitledModel, LocationModel):
    description = models.TextField(max_length=500, blank=True)
    domain = models.URLField(
        blank=True,
        help_text=_("Domain in showcase page. Leave blank to use the one in .env"),
    )

    default = UniqueBooleanField(default=False)
    enabled = models.BooleanField(
        default=True,
        help_text=_("Set to False to hide it in views, unless is chosen as default"),
    )

    places = models.ManyToManyField(Place, blank=True)

    reload_time = models.PositiveIntegerField(
        null=False,
        blank=False,
        default=300,
        help_text=_("Reload time (in seconds) for showcase page"),
    )

    provider = models.ForeignKey(
        LeafletProvider,
        on_delete=models.PROTECT,
        help_text="The map provider to use with leaflet map",
    )

    zoom_initial = models.PositiveSmallIntegerField(default=15)
    zoom_min = models.PositiveSmallIntegerField(default=13)
    zoom_max = models.PositiveSmallIntegerField(default=20)

    logo_event = models.ForeignKey(
        Logo,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        default=None,
        related_name="+",
    )
    logo_organizer = models.ForeignKey(
        Logo,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        default=None,
        related_name="+",
    )
    logo_partners = models.ManyToManyField(to=Logo, related_name="+", blank=True)

    @property
    def centroid(self) -> Point:
        if self.places.count() <= 1:
            return self.location
        return self.places.aggregate(centroid=Centroid(Union("location")))["centroid"]

    @property
    def zoom(self):
        return {
            "initial": self.zoom_initial,
            "min": self.zoom_min,
            "max": self.zoom_max,
        }

    def set_centroid(self):
        self.location = self.centroid
        self.save()

    @classmethod
    def get_default(cls) -> "Landscape":
        return get_object_or_404(cls, default=True)

    class VisibleLandscapeManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(Q(enabled=True) | Q(default=True))

        def get_default(self):
            return self.get(default=True)

    objects = models.Manager()
    visible_objects = VisibleLandscapeManager()

    class Meta:
        constraints = [
            models.CheckConstraint(
                name="zoom_min <= zoom_initial",
                check=Q(zoom_min__lte=F("zoom_initial")),
            ),
            models.CheckConstraint(
                name="zoom_max >= zoom_initial",
                check=Q(zoom_max__gte=F("zoom_initial")),
            ),
        ]

apps/website/forms.py
import django.forms
from django.contrib.gis.forms import CharField, DecimalField, Textarea
from django.utils.translation import gettext as _


class ShareForm(django.forms.Form):
    message = CharField(
        label=_("Esprimi la tua voce"),
        help_text=_(
            "Scrivi il tuo pensiero qui o usa il microfono per "
            "registrare e trascrivere la tua voce (max 30 secondi)"
        ),
        widget=Textarea,
        max_length=500,  # TODO: find a way to use same value in form and model
    )

    latitude = DecimalField(label=_("Latitudine"))
    longitude = DecimalField(label=_("Longitudine"))

apps/website/views.py
import datetime as dt
from collections import defaultdict
from typing import Iterable

from django.contrib import messages
from django.contrib.gis.geos import Point
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Max, Min
from django.shortcuts import get_object_or_404, redirect
from django.utils import timezone
from django.utils.translation import gettext as _
from django.views.generic import TemplateView

from . import forms, models


class LandscapeTemplateView(TemplateView):
    def get_landscape(self):
        try:
            slug = self.request.COOKIES.get("landscape")
            return models.Landscape.visible_objects.get(slug=slug)
        except ObjectDoesNotExist:
            return get_object_or_404(models.Landscape.visible_objects, default=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["landscape"] = self.get_landscape()
        context["landscapes"] = models.Landscape.visible_objects.values_list(
            "slug", "title"
        )
        return context

    def render_to_response(self, context, **response_kwargs):
        response = super().render_to_response(context, **response_kwargs)
        response.set_cookie(
            "landscape", context["landscape"].slug, path="/", samesite="Lax"
        )
        return response


class MapTemplateView(LandscapeTemplateView):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        landscape: models.Landscape = context["landscape"]
        centroid = landscape.centroid

        context.setdefault("center", [centroid.y, centroid.x])
        context.setdefault("zoom", landscape.zoom)
        context.setdefault("provider", landscape.provider.as_json())
        context.setdefault(
            "places", [place.as_json() for place in context["landscape"].places.all()]
        )

        return context


class Share(LandscapeTemplateView):
    template_name = "website/share.html"

    def post(self, request):
        form = forms.ShareForm(request.POST)

        if form.is_valid():
            message = form.cleaned_data["message"]

            latitude = float(form.cleaned_data["latitude"])
            longitude = float(form.cleaned_data["longitude"])
            location = Point(x=longitude, y=latitude)

            landscape = self.get_landscape()

            share = models.Share(
                message=message, location=location, landscape=landscape
            )
            share.save()
            messages.success(request, _("Grazie per la condivisione"))
            return redirect("website:map")

        context = self.get_context_data(form=form)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.setdefault("form", forms.ShareForm())
        context.setdefault("places", context["landscape"].places.all())
        return context


class Map(MapTemplateView):
    template_name = "website/map.html"


class HistoryMap(MapTemplateView):
    template_name = "website/history.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        timestamp = kwargs.get("timestamp", timezone.now())
        timestamp_range = models.Share.objects.aggregate(
            min=Min("timestamp"), max=Max("timestamp")
        )
        timestamp_min = timestamp_range["min"].date()
        timestamp_max = timestamp_range["max"].date()
        if timestamp.date() > timestamp_max:
            timestamp = timezone.datetime.combine(timestamp_max, dt.time(23, 00))

        context["timestamp"] = {
            "current": timestamp,
            "first_date": timestamp_min,
            "last_date": timestamp_max,
        }
        context["date_range"] = list(date_range(timestamp_min, timestamp_max))
        context["time_range"] = [dt.time(h, 0) for h in range(24)]

        counters = {
            place: defaultdict(lambda: 0) for place in models.Place.objects.all()
        }

        timestamp_limit = timestamp + dt.timedelta(hours=1)
        for share in models.Share.objects.filter(timestamp__lt=timestamp_limit):
            for word in share.words.all():
                counters[share.place][word] += 1

        output = []
        for place, counter in counters.items():
            if not counter:
                continue
            max_value = max(counter.values())
            frequencies = [
                [word.text, count / max_value] for word, count in counter.items()
            ]
            output.append(
                {"coordinates": place.coordinates, "frequencies": frequencies}
            )

        context["places"] = output

        return context


def date_range(first_date: dt.date, last_date: dt.date) -> Iterable[dt.date]:
    date = first_date
    while date <= last_date:
        yield date
        date += timezone.timedelta(days=1)

apps/website/templates/website/history.html
{% extends "website/map.html" %}

{% load static %}

{% block main %}
<main id="history-page" class="w-100 flex-grow flex flex-row">
  <section id="description" 
           class="w-20 tc mv1 mr1 pa2 flex flex-column justify-around items-center outline">
    
    <section class="flex flex-column justify-center">
      <section id="date-range" class="flex flex-row flex-wrap justify-center mv3">
        {% for date in date_range %}
          <a type="button" data-date="{{ date | date:"Y-m-d" }}"  
             onclick="selectDate(this)" href="javascript:void(0)"
             class="link f5 b ma2 pa2 br-pill ba bw2 gray b--gray">
            {{ date | date:"d M" }}
          </a>
        {% endfor %}
      </section>
        
      <section id="time-range" class="flex flex-row flex-wrap justify-center ma3">
        {% for time in time_range %}
          <a type="button" data-time="{{ time | time }}"  
             onclick="selectTime(this); update();" href="javascript:void(0)"
             class="link f6 ma1 pa1 br-pill ba bw1 gray b--gray grow pointer">
            {{ time | time }}
          </a>
        {% endfor %}
      </section>
    </section>
    
    <section class="flex flex-row flex-wrap justify-around items-center ma3">
      <section class="flex flex-column ma3">
        <label for="date">Seleziona il giorno</label>
        <input id="date" type="date" 
               value="{{ timestamp.current | date:"Y-m-d" }}"
               min="{{ timestamp.first_date | date:"Y-m-d" }}"
               max="{{ timestamp.last_date | date:"Y-m-d" }}">  
      </section>
      
      <section class="flex flex-column ma3">
        <label for="time">Seleziona l'orario</label>
        <input id="time" type="time" class="tc" 
               value="{{ timestamp.current | time }}">
      </section>
      
      <section class="w-100 ma3 flex flex-center">
        <a class="link grow pa2 ba bw2 b--black br4 pointer" 
           type="button" onclick="update()">
          Aggiorna
        </a>
      </section>
      
    </section>
  </section>
    
  <section id="full-map" class="w-80 mv1 ml1 pa2 outline">
    <div id="map" style="height: 100%;"></div>  
  </section>
</main>
{% endblock %}

{% block scripts %}
  {{ block.super }}
  
  <script defer>  
    function update() {
        const date = $("input#date").val();
        const time = $("input#time").val();
        window.location.href = `{% url "website:history" %}${date}T${time}:00`;
    }
    
    function selectDate(button) {
        $("section#date-range > a.link")
            .addClass("grow pointer gray b--gray")
            .removeClass("near-black b--near-black");
            
        $(button)
            .addClass("near-black b--near-black")
            .removeClass('grow pointer gray b--gray');
            
        $("input#date").val($(button).attr("data-date"));
    }
    
    function selectTime(button) {
        $("section#time-range > a.link")
            .removeClass("b near-black b--near-black").addClass("gray b--gray");
        
        if($(button).length <= 0) return; 
        $(button)
            .removeClass('gray b--gray').addClass("b near-black b--near-black");
        $("input#time").val($(button).attr("data-time"));
    }
    
    document.addEventListener('DOMContentLoaded', () => {
        const current = {
            date: "{{ timestamp.current | date:"Y-m-d" }}",
            time: "{{ timestamp.current | time }}",
        };
                
        selectDate($(`section#date-range > a.link[data-date='${current.date}']`));
        selectTime($(`section#time-range > a.link[data-time='${current.time.substring(0, 2)}:00']`));
        $("input#time").val(current.time);
    });
  </script>
{% endblock %}

apps/website/templates/website/map.html
{% extends "base.html" %}

{% load static %}
{% load sass_tags %}

{% block stylesheet %}
  {{ block.super }}
  <link type="text/css" rel="stylesheet" href="{% sass_src 'website/css/map.scss' %}">
{% endblock %}


{% block contents %}
  <div id="map" style="width: 100%; height: calc(100vh - 4rem - 2.5rem)"></div>
{% endblock %}

{% block scripts %}  
  <script src="https://unpkg.com/leaflet@latest/dist/leaflet.js" defer></script>
  <script src="https://unpkg.com/leaflet-providers@2.0.0/leaflet-providers.js" defer></script>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/wordcloud2.js/1.0.2/wordcloud2.min.js" 
          integrity="sha512-f1TzI0EVjfhwKkLEFZnu8AgzzzuUBE9X4YY61EoQJhjH8m+25VKdWmEfTJjmtnm0TEP8q9h+J061kCHvx3NJDA==" 
          crossorigin="anonymous" referrerpolicy="no-referrer" defer></script>
  
  <script src="{% static 'website/js/map.js' %}" defer></script>
  <script defer>
    const options = {
      zoom: { 
        initial: {{ zoom.initial }}, 
        min: {{ zoom.min }}, 
        max: {{ zoom.max }} 
      },
      map: { 
        provider: { 
          name: "{{provider.name}}", 
          url: "{{ provider.url }}" 
        }
      }
    }
    document.addEventListener('DOMContentLoaded', () => 
        new LeafletMap("map", {{ center }}, options).addWordClouds({{ places | safe }})
    );
  </script>
{% endblock %}

apps/website/templates/website/share.html
{% extends "base.html" %}

{% load static %}
{% load sass_tags %}

{% block stylesheet %}
  {{ block.super }}
  <link type="text/css" rel="stylesheet" href="{% sass_src 'website/css/share.scss' %}">
{% endblock %}


{% block main %}
  <main class="w-100 outline mv1 flex-grow 
               flex flex-column justify-center justify-center-ns items-center">
    <p class="f4 mb4 cit tc">Quale frase emerge nella tua mente attraversando questo spazio?</p>
    <form action="" method="post" 
          class="flex flex-column flex-center w-100 mw7 pa2">
      {% csrf_token %}
    
      {% for error in form.non_field_errors %}
        <span class="w-100 f6 red b">{{ error }}</span>
      {% endfor %}
    
      <section id="message-section" class="widget-tab w-100 flex flex-row flex-wrap justify-center">
        <label for="{{ form.message.id_for_label }}" class="w-100 mt2 mb2 tc">
          {{ form.message.label }}
        </label>
        <div id="text-container" class="w-100 flex flex-row flex-wrap">
          <textarea id="{{ form.message.id_for_label }}" name="{{ form.message.html_name }}"
                  rows="7" cols="10" placeholder="{{ form.message.help_text }}"
                  class="tc w-100" maxlength="500" required>{{ form.message.value | default:'' }}</textarea>
          {% for error in form.message.errors %}
            <span class="w-100 f6 red b">{{ error }}</span>
          {% endfor %}
        </div>
        
        <a id="record-button" type="button" 
           class="link flex flex-center w3 h3 white mv3 mh4 br4 grow">
          <i data-feather="mic" class="w2 h2"></i>
        </a>
        <a id="reset-button" type="button" 
           class="link flex flex-center w3 h3 black mv3 mh4 br4 ba bw2 b--black bg-white grow">
          <i data-feather="trash-2" class="w2 h2"></i>
        </a>

      </section>
    
      <section id="location-section" class="widget-tab flex flex-row justify-center flex-wrap">
      
        <div id="text-preview" class="tc w-100 measure-wide pa2 mv2 mb4 mid-gray"></div>
      
        <div id="location-auto-icon" 
             class="w-100 w-50-l h4 pa3 br-l bw1 b--black gray
                    flex flex-column items-center justify-between">
          <label class="b w-100 tc ttu">Clicca per ottenere la posizione</label> 
          <div class="w-100 tc">
            <i data-feather="map-pin" class="b i3 gray grow" data-state="waiting"></i>
          </div>
        </div>
        
        <p class="w-100 ttu gray tc dn-l">Oppure</p>
      
        <div id="location-place" class="w-100 w-50-l pa3 h4 tc flex flex-column items-center justify-between">
          <label for="place" class="gray b w-100 tc ttu">
            Seleziona un punto di interesse
          </label>
          <div class="h-100 flex flex-column justify-center">
            <select name="place" id="place" class="tc">
              <option selected></option>
              
              {% for place in places %}
                <option class="tc" value="{{ place.id }}" title="{{ place.title }}"
                        data-latitude="{{ place.latitude | floatformat:'7u' }}"
                        data-longitude="{{ place.longitude | floatformat:'7u' }}">
                  {{ place.title|truncatewords:5 }}
                </option>
              {% endfor %}
            </select>
          </div>
        </div>
        
        <div hidden class="pa1 w-50-ns">
          <label for="{{ form.latitude.id_for_label }}">{{ form.latitude.label }}</label>
          <input id="{{ form.latitude.id_for_label }}" name="{{ form.latitude.html_name }}"
                 type=number step="any" class="w-100" required readonly>
        </div>        
        <div hidden class="pa1 w-50-ns">
          <label for="{{ form.longitude.id_for_label }}">{{ form.longitude.label }}</label>
          <input id="{{ form.longitude.id_for_label }}" name="{{ form.longitude.html_name }}"
                 type=number step="any" class="w-100" required readonly>
        </div>
      </section>
    
      <div id="location-display" class="gray w-100 tc mv2 pa2">
        <p id="location-display-title">&nbsp;</p>
        <p id="location-display-coordinates"></p>
        
        {% for error in form.latitude.errors %}
          <p class="w-100 f6 red b">{{ error }}</p>
        {% endfor %}
        
        {% for error in form.longitude.errors %}
          <p class="w-100 f6 red b">{{ error }}</p>
        {% endfor %}
      </div>
      
      <div id="share-section" class="w-100 flex flex-row justify-between items-center pa2">
        <a id="prev-tab-button" type="button" class="link dim flex flex-center w2 h2">
          <i data-feather="arrow-left-circle" class="w2 h2"></i>
        </a>
        
        <input id="submit-button" type="submit" class="pa1 grow" value="Partecipa!" disabled>
        
        <a id="next-tab-button" type="button" class="link dim flex flex-center w2 h2">
          <i data-feather="arrow-right-circle" class="w2 h2"></i>
        </a>
      </div>
    </form>
  </main>
{% endblock %}


{% block scripts %}
  
  <script src="https://unpkg.com/feather-icons" defer></script>
  <script defer>
    document.addEventListener('DOMContentLoaded', () => feather.replace());
  </script>
  
  <script src="https://unpkg.com/axios/dist/axios.min.js" defer></script>
  <script src="{% static 'website/js/share.js' %}" defer></script>
  
  <script defer>
    document.addEventListener('DOMContentLoaded', () => {
        new TabWidget(
            $("#prev-tab-button > svg"),
            $("#next-tab-button > svg"),
        );
        const widget = new ShareWidget(
            $("input#{{ form.latitude.id_for_label }}"),
            $("input#{{ form.longitude.id_for_label }}"),
            $("textarea#{{ form.message.id_for_label }}"),
            $("#text-preview")
        );
        
        $(`section#message-section a#reset-button`).click(() => widget.resetMessage());
    });
  </script>
  
  <script src="{% static 'speech/js/speech.js' %}" defer></script>
  <script defer>
    document.addEventListener('DOMContentLoaded', () => {
        const stt = new SpeechToText(
            $("a#record-button"),
            $("#text-container > textarea"),
            "{% url "stt" %}",
        );
    })
  </script>
  
{% endblock %}