admin/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    # apps
    path("", include("apps.website.urls", namespace="website")),
    path("showcase/", include("apps.showcase.urls", namespace="showcase")),
    path("api/", include("apps.api.urls")),
    path("api/speech/", include("apps.speech.urls")),
    # Static pages
    path("info/", TemplateView.as_view(template_name="info.html"), name="info"),
    path(
        "privacy/", TemplateView.as_view(template_name="privacy.html"), name="privacy"
    ),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    # Third party libraries
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/website/urls.py
from django.urls import path, register_converter
from django.utils import timezone

from . import views


class DateTimeConverter:
    regex = r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}"

    @staticmethod
    def to_python(value):
        time = timezone.datetime.strptime(value, "%Y-%m-%dT%H:%M:%S")
        return timezone.make_aware(time)

    @staticmethod
    def to_url(value):
        return value


register_converter(DateTimeConverter, "datetime")

app_name = "website"
urlpatterns = [
    path("", views.Map.as_view()),
    path("map/", views.Map.as_view(), name="map"),
    path("share/", views.Share.as_view(), name="share"),
    path("history/", views.HistoryMap.as_view(), name="history"),
    path("history/<datetime:timestamp>/", views.HistoryMap.as_view(), name="history"),
]

templates/_alerts.html
<section id="alert-list" class="flex flex-column"></section>

templates/_footer.html
<section class="flex flex-row flex-wrap justify-around w-100">
  <a href="https://afor.dev" class="link b dim dib mr3 pa1">afor.dev</a>
  <a href="{% url 'privacy' %}" class="link dim dib mr3 pa1">Privacy</a>
  <a href="https://github.com/archiviofontiorali/voice-landscape" class="link b dim dib mr3 pa1">github</a>
</section>

templates/_header.html
<nav class="flex flex-row justify-around f6 fw6 ttu tracked overflow-x-auto pa1">
  <a href="{% url 'website:map' %}" class="link dib mr3 pa1">Mappa</a>
  <a href="{% url 'website:share' %}" class="link dib pa1">Partecipa</a>
  <a href="{% url 'info' %}" class="link dib mr3 pa1">Info</a>
  
  {% if landscapes and landscapes|length > 1 %}
  <label for="landscape-select"></label>
  <select id="landscape-select" name="landscape-select"
          onchange="document.cookie = `landscape=${this.value}; Path=/; Samesite=Lax`; location.reload();">
    {% for slug, title in landscapes %}
    <option value="{{ slug }}" {% if slug == landscape.slug %}selected{% endif %}>
      {{ title }}
    </option>
    {% endfor %}
  </select>
  {% endif %}
</nav>

templates/_scripts.html
{% load static %}

<script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous" defer></script>

<script src="{% static 'js/alerts.js' %}" defer></script>
<script defer>
  {% if messages %}
  document.addEventListener('DOMContentLoaded', () => {
      {% for message in messages %}
      showAlert("{{ message }}", AlertLevel.{{ message.tags|default:'info'|upper }});
      {% endfor %}
  });
  {% endif %}
</script>

templates/base.html
{% load static %}
{% load sass_tags %}

<!DOCTYPE html>
<html lang="it" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1">
  
  {% block custom_meta %}{% endblock %}
  
  <title>{{ title | default:'AFOr | Paesaggio di Voci' }}</title>

  <link rel="stylesheet" href="https://unpkg.com/tachyons@4.12.0/css/tachyons.min.css"/>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
        integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin=""/>

  <link type="text/css" rel="stylesheet" href="{% sass_src 'css/alerts.scss' %}">
  <link type="text/css" rel="stylesheet" href="{% sass_src 'css/main.scss' %}">

  {% block stylesheet %}{% endblock %}

  <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
</head>
<body class="flex flex-column min-vh-100 pa2">
  
  {% block header %}
    <header class="w-100 outline mb1">{% include "_header.html" %}</header>
  {% endblock %}
  
  {% block alerts %}
    <header id="alert-box" class="w-100">{% include "_alerts.html" %}</header>
  {% endblock %}

  {% block main %}
    <main class="w-100 outline mv1 flex-grow flex flex-center">
      {% block contents %}{% endblock %}
    </main>  
  {% endblock %}

  {% block footer %}
    <footer class="w-100 outline mt1">{% include "_footer.html" %}</footer>
  {% endblock %}

  {% include "_scripts.html" %}
  {% block scripts %}{% endblock %}

</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block contents %}
  <article class="f4 tj tc-ns measure-wide center pa1">  
    <h1 class="f1">Paesaggi di Voci</h1>
  
    <p class="f3">
      Come percepisci lo <b>spazio</b>? <br>In che modo la tua <b>voce</b> influenza lo spazio in cui ti muovi?
    </p>
    
    <h2>Di cosa si tratta?</h2>
    <p class="f4">
      <b>Paesaggi di Voci</b> è un esperimento collettivo di raccolta e analisi su come 
      le nostre parole si definiscono nello spazio e possano aiutarci a descriverlo.
    </p>
    <p class="f4">
      Attraverso questa semplice <a href="{% url 'share' %}">applicazione web</a> chiunque
      può partecipare all’esperimento, condividendo - sotto forma di tracce digitali 
      testuali e audio - le considerazioni sullo spazio che attraversano.
    </p>
    <p class="f4">
      Le voci raccolte vengono elaborate e visualizzate all’interno di una 
      <a href="{% url 'map' %}">mappa</a> interattiva. La <a href="{% url 'map' %}">mappa</a> consente di 
      avere una immediata percezione dei luoghi e di come vengono percepiti.
    </p>
    
    <h2>Come partecipare?</h2>
    <ul class="list pl0 ba b--silver">
      <li class="pa1 ba b--silver">Entra nella sezione <a href="{% url 'share' %}">PARTECIPA</a></li>
      <li class="pa1 ba b--silver">Scrivi o registra un messaggio</li>
      <li class="pa1 ba b--silver">Rileva la tua posizione GPS (dovrai consentire l'accesso)</li>
      <li class="pa1 ba b--silver">Invia la tua <b>voce</b></li>
      <li class="pa1 ba b--silver">
        Entra nella <a href="{% url 'map' %}">MAPPA</a> per vedere come cambia il paesaggio
      </li>
    </ul>

    <hr>
    
    <h2>Voglio saperne di più!!!</h2>
    <p class="f4">
      La prima installazione di <b>Paesaggio di Voci</b>, è stata proposta come nostro 
      contributo al <b>Festival Filosofia 2021</b> (tema: libertà).
    </p>
    <p>      
      Il 17 Dicembre 2022 Paesaggio di Voci è stato riproposto durante l'evento 
      <a href="https://afor.dev/events/riuso-creativo-2022/">
        Riuso Creativo degli Archivi di Fonti Orali
      </a>
      in occasione della geo-esplorazione dei luoghi del villaggio artigiano di modena ovest.
    </p>
  </article>
{% endblock %}

templates/info.html
{% extends "base.html" %}

{% block contents %}
  <article class="w-100 pa2 pa0-l f4 tj tc-ns flex 
                  flex-column items-center 
                  flex-row-l flex-wrap-l justify-around-l items-center-l">
    
    <section class="measure">
      <h1 class="f1">Paesaggio di Voci</h1>
      <p class="f3 tl tc-ns cit">Come percepisci lo <b>spazio</b>?</p>
      <p class="f3 tl tc-ns cit">Quali <b>parole</b> emergono da questa percezione?</p>
      <p class="f3 tl tc-ns cit">In che modo le nostre <b>voci</b> contribuiscono a creare lo spazio che abitiamo?</p>
            
      <p class="f4">
        <b>Paesaggio di Voci</b> è un esperimento collettivo di raccolta e analisi su come
        le nostre parole definiscono lo spazio e ci aiutano a descriverlo.
      </p>
      
      <p class="f4">
        Attraverso questa semplice <a class="link" href="{% url 'website:share' %}">applicazione web</a> chiunque
        può partecipare all’esperimento, condividendo - sotto forma di tracce digitali 
        testuali e audio - frammenti del proprio <i>paesaggio linguistico</i> (parole e 
        frasi, affetti e significati).
      </p>
      
      <p class="f4">
        Le voci raccolte vengono elaborate e visualizzate all’interno di una 
        <a class="link" href="{% url 'website:map' %}">mappa</a> interattiva, i cui risultati verranno 
        discussi il 17 Settembre durante l’evento 
        <a class="link" href="https://www.festivalfilosofia.it/index.php?mod=ff_eventi&id=25253">
          La parola come racconto collettivo
        </a>
      </p>
      
    </section>
  
    <section class="measure">
      <h2>Come partecipare?</h2>
      
      <ul class="list pl0 ba b--silver">
        <li class="pa1 ba b--silver">Entra nella sezione <a class="link" href="{% url 'website:share' %}">PARTECIPA</a></li>
        <li class="pa1 ba b--silver">Scrivi o registra un messaggio</li>
        <li class="pa1 ba b--silver">Rileva la tua posizione GPS (dovrai consentire l'accesso)</li>
        <li class="pa1 ba b--silver">Invia la tua <b>voce</b></li>
        <li class="pa1 ba b--silver">
          Entra nella <a class="link" href="{% url 'website:map' %}">MAPPA</a> per vedere come cambia il paesaggio
        </li>
      </ul>
      
      <h2>Per saperne di più!</h2>
      <p class="f4">
        La prima installazione di <b>Paesaggio di Voci</b>, è stata proposta come nostro 
        contributo al <b>Festival Filosofia 2021</b> (tema: libertà).
      </p>
      <p>      
        Il 17 Dicembre 2022 Paesaggio di Voci è stato riproposto durante l'evento:
        <a class="link" href="https://afor.dev/events/riuso-creativo-2022/">
          Riuso Creativo degli Archivi di Fonti Orali
        </a> in occasione della geo-esplorazione dei luoghi del villaggio artigiano di 
        modena ovest.
      </p>

    </section>
  </article>
{% endblock %}

templates/privacy.html
{% extends "base.html" %}

{% block contents %}
  <article class="measure center tj">
    <h1>Privacy Policy</h1>
    <p>
      Questo sito non raccoglie ne memorizza intenzionalmente nessun tipo di dato 
      personale e/o sensibile.   
    </p>
    
    <p>
      I visitatori del sito possono, nella sezione "partecipa" inserire un messaggio e 
      la propria posizione. Il messaggio e localizzazione vengono salvati così come 
      inviati insieme alla data e all'ora del contributo. Queste informazioni vengono 
      conservate solo per scopi tecnici durante la durata dell'evento ed eventualmente 
      cancellati alla fine dello stesso. 
      
      In nessun caso, nessuna informazioni personale eventualmente condivisa verrà resa 
      pubblica volontariamente. Gli unici dati resi pubblici saranno i dati aggregati 
      (frequenze e parole più usate) e/o i dati sull'utilizzo del sito.
      
      L'utente non viene tracciato in alcun modo, ogni contributo è salvato a se stante.
      Non teniamo traccia ne dell'indirizzo IP, ne del dispositivo, ne in alcun modo 
      della persona che invia contributi al sito.
    </p>
     
    <p>
      Nel caso di messaggi vocali, l'audio verrà inviato al server solamente per essere 
      trascritto. Il file audio e la trascrizione non vengono salvati.
    </p>
    
    <p>
      Questo sito non fa uso di cookie di terze parti di alcun genere, ne di software 
      di “analytics”.
      Questo sito non profila l'utente in alcun modo.
      
      Gli unici cookie utilizzati sono di natura tecnica e interni al sito. Questi 
      vengono creati questioni di criptazione e sicurezza come il CSRF 
      (<a href="https://it.wikipedia.org/wiki/Cross-site_request_forgery">wikipedia</a>)
      o per tenere traccia delle preferenze del dispositivo dell'utente come il tema grafico
      o l'ultima mappa aperta (in questo momento ne viene generato uno solo in caso di 
      diverse configurazioni della mappa).
    </p>
  </article>
  
{% endblock %}